import { RTE_CONTENT_LABELS, RTE_SLASH_LABELS } from '@cds/rte-core/extensions';
import type { RteLabels } from './types';

/** Rótulos em inglês (padrão), congelados em profundidade. */
export const RTE_LABELS_EN: RteLabels = Object.freeze({
  content: RTE_CONTENT_LABELS.en,
  slash: RTE_SLASH_LABELS.en,
  editor: Object.freeze({ ariaLabel: 'Rich text editor' }),
  toolbar: Object.freeze({
    toolbar: 'Formatting',
    undo: 'Undo',
    redo: 'Redo',
    blockType: 'Text style',
    paragraph: 'Paragraph',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strike: 'Strikethrough',
    code: 'Inline code',
    superscript: 'Superscript',
    subscript: 'Subscript',
    textColor: 'Text color',
    highlight: 'Highlight',
    defaultColor: 'Default color',
    bulletList: 'Bulleted list',
    orderedList: 'Numbered list',
    taskList: 'Task list',
    indent: 'Increase indent',
    outdent: 'Decrease indent',
    align: 'Alignment',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    blockquote: 'Quote',
    codeBlock: 'Code block',
    codeLanguage: 'Code language',
    plainText: 'Plain text',
    horizontalRule: 'Horizontal line',
    table: 'Table',
    insertTable: 'Insert table',
    addRowBefore: 'Insert row above',
    addRowAfter: 'Insert row below',
    addColumnBefore: 'Insert column before',
    addColumnAfter: 'Insert column after',
    deleteRow: 'Delete row',
    deleteColumn: 'Delete column',
    deleteTable: 'Delete table',
    mergeCells: 'Merge cells',
    splitCell: 'Split cell',
    toggleHeaderRow: 'Header row',
    toggleHeaderColumn: 'Header column',
    spanLimit: 'Unavailable: a cell would span more than 100 rows or columns.',
    callout: 'Callout box',
    removeCallout: 'Remove box',
    pullquote: 'Pull quote',
    readAlso: '"Read also" box',
    clearFormatting: 'Clear formatting',
    heading: (level: 2 | 3 | 4) => `Heading ${level}`,
    colorNames: Object.freeze({
      gray: 'Gray',
      red: 'Red',
      orange: 'Orange',
      green: 'Green',
      blue: 'Blue',
      purple: 'Purple',
      pink: 'Pink',
      teal: 'Teal',
      yellow: 'Yellow',
    }),
  }),
  errors: Object.freeze({
    rteRequired: 'This field is required.',
    rteMaxChars: ({ max, actual }: { max: number; actual: number }) =>
      `Use at most ${max} characters (${actual} now).`,
    rteMaxWords: ({ max, actual }: { max: number; actual: number }) =>
      `Use at most ${max} words (${actual} now).`,
  }),
});
