import { RTE_CONTENT_LABELS, RTE_SLASH_LABELS } from '@cds/rte-core/extensions';
import type { RteLabels } from './types';

/** Rótulos em inglês (padrão), congelados em profundidade. */
export const RTE_LABELS_EN: RteLabels = Object.freeze({
  content: RTE_CONTENT_LABELS.en,
  slash: RTE_SLASH_LABELS.en,
  editor: Object.freeze({ ariaLabel: 'Rich text editor' }),
  toolbar: Object.freeze({
    toolbar: 'Formatting',
    undo: 'Undo',
    redo: 'Redo',
    blockType: 'Text style',
    paragraph: 'Paragraph',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strike: 'Strikethrough',
    code: 'Inline code',
    superscript: 'Superscript',
    subscript: 'Subscript',
    textColor: 'Text color',
    highlight: 'Highlight',
    defaultColor: 'Default color',
    bulletList: 'Bulleted list',
    orderedList: 'Numbered list',
    taskList: 'Task list',
    indent: 'Increase indent',
    outdent: 'Decrease indent',
    align: 'Alignment',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    blockquote: 'Quote',
    codeBlock: 'Code block',
    codeLanguage: 'Code language',
    plainText: 'Plain text',
    horizontalRule: 'Horizontal line',
    table: 'Table',
    link: 'Link',
    editLink: 'Edit link',
    lang: 'Language',
    editLang: 'Edit language',
    quoteAuthor: 'Quote author',
    insertTableCustom: 'Insert table…',
    insertTable: 'Insert table 3 × 3',
    addRowBefore: 'Insert row above',
    addRowAfter: 'Insert row below',
    addColumnBefore: 'Insert column before',
    addColumnAfter: 'Insert column after',
    deleteRow: 'Delete row',
    deleteColumn: 'Delete column',
    deleteTable: 'Delete table',
    mergeCells: 'Merge cells',
    splitCell: 'Split cell',
    toggleHeaderRow: 'Header row',
    toggleHeaderColumn: 'Header column',
    spanLimit: 'Unavailable: a cell would span more than 100 rows or columns.',
    callout: 'Callout box',
    removeCallout: 'Remove box',
    pullquote: 'Pull quote',
    readAlso: '"Read also" box',
    clearFormatting: 'Clear formatting',
    image: 'Insert image',
    editImage: 'Edit image',
    video: 'Insert video',
    editVideo: 'Edit video',
    embed: 'Insert embedded content',
    editEmbed: 'Edit embedded content',
    heading: (level: 2 | 3 | 4) => `Heading ${level}`,
    colorNames: Object.freeze({
      gray: 'Gray',
      red: 'Red',
      orange: 'Orange',
      green: 'Green',
      blue: 'Blue',
      purple: 'Purple',
      pink: 'Pink',
      teal: 'Teal',
      yellow: 'Yellow',
    }),
  }),
  errors: Object.freeze({
    rteRequired: 'This field is required.',
    rteMaxChars: ({ max, actual }: { max: number; actual: number }) =>
      `Use at most ${max} characters (${actual} now).`,
    rteMaxWords: ({ max, actual }: { max: number; actual: number }) =>
      `Use at most ${max} words (${actual} now).`,
  }),
  dialogs: Object.freeze({
    apply: 'Apply',
    cancel: 'Cancel',
    remove: 'Remove',
    linkInsertTitle: 'Insert link',
    linkEditTitle: 'Edit link',
    linkUrl: 'Address (URL)',
    linkUrlHint:
      'For example: site.com, name@site.com or https://site.com/page',
    linkText: 'Text',
    linkNewTab: 'Open in a new tab',
    linkRemove: 'Remove link',
    langTitle: 'Mark language',
    langEditTitle: 'Edit language',
    langLanguage: 'Language',
    langOther: 'Other…',
    langCode: 'Language code (BCP 47)',
    langCodeHint: 'For example: pt-BR, en-GB, zh-Hant',
    langDirection: 'Text direction',
    langDirectionDefault: 'Default',
    langDirectionLtr: 'Left to right',
    langDirectionRtl: 'Right to left',
    langRemove: 'Remove language',
    quoteTitle: 'Quote author',
    quoteAuthor: 'Author',
    quoteRole: 'Role',
    tableTitle: 'Insert table',
    tableRows: 'Rows',
    tableColumns: 'Columns',
    tableHeaderRow: 'Header row',
    tableHeaderColumn: 'Header column',
    tableInsert: 'Insert',
    errorRequired: 'Fill in this field.',
    errorLinkUrl:
      'Address not accepted. Check the format or use another address.',
    errorLangCode: 'Invalid code. Use a BCP 47 tag such as pt-BR.',
    errorRange: (min: number, max: number) =>
      `Enter a whole number from ${min} to ${max}.`,
    errorMaxLength: (max: number) => `Use at most ${max} characters.`,
    imageInsertTitle: 'Insert image',
    imageEditTitle: 'Image details',
    imageUrl: 'Image address (URL)',
    videoUrl: 'Video address (URL)',
    imageUrlHint: 'Use https://… or a path starting with /.',
    imageAlt: 'Alternative text',
    imageDecorative: 'Decorative image',
    imageAltHint:
      'Describe what the image shows. Mark "Decorative image" only if it adds no information.',
    imageCaption: 'Caption',
    imageCredit: 'Credit',
    imageAlign: 'Alignment',
    imageWidth: 'Width (px)',
    imageWidthHint: 'Leave empty for the natural size.',
    videoInsertTitle: 'Insert video',
    videoEditTitle: 'Video details',
    videoPoster: 'Cover image address (optional)',
    videoCaption: 'Caption',
    videoTracks: 'Text tracks',
    videoTrackKind: 'Type',
    videoTrackCaptions: 'Captions (dialogue and sounds)',
    videoTrackSubtitles: 'Subtitles (translation)',
    videoTrackUrl: 'Track address (.vtt)',
    videoTrackLang: 'Language code (BCP 47)',
    videoTrackLabel: 'Label',
    videoTrackDefault: 'Default',
    videoTrackAdd: 'Add track',
    videoCaptionsHint:
      'No captions track: videos with speech or meaningful sound need one (WCAG 1.2.2).',
    embedInsertTitle: 'Insert embedded content',
    embedEditTitle: 'Embedded content details',
    embedUrl: 'Page address (URL)',
    embedCaption: 'Caption',
    errorMediaUrl:
      'Address not accepted. Use https:// or a path starting with /, on an allowed host.',
    errorEmbedUrl: 'No enabled provider recognizes this address.',
    videoUrlHint: 'Use https://… or a path starting with /.',
    videoTrack: (n: number) => `Track ${n}`,
    videoTrackRemove: (n: number) => `Remove track ${n}`,
    embedUrlHint: (providers: readonly string[]) =>
      `Accepted: ${providers.join(', ')}.`,
    languageNames: Object.freeze({
      en: 'English',
      es: 'Spanish',
      fr: 'French',
      de: 'German',
      it: 'Italian',
      pt: 'Portuguese',
      la: 'Latin',
      ja: 'Japanese',
      zh: 'Chinese',
      ru: 'Russian',
      ar: 'Arabic',
      he: 'Hebrew',
    }),
  }),
  floating: Object.freeze({
    textMenu: 'Text formatting',
    linkMenu: 'Link',
    tableMenu: 'Table',
    imageMenu: 'Image',
    openLink: 'Opens in a new tab',
    removeLink: 'Remove link',
    tableMore: 'More table operations',
    imageAlignLeft: 'Align left',
    imageAlignCenter: 'Center',
    imageAlignRight: 'Align right',
    imageAlignFull: 'Full width',
    removeImage: 'Remove image',
    videoMenu: 'Video',
    embedMenu: 'Embedded content',
    imageDetails: 'Image details…',
    videoDetails: 'Video details…',
    embedDetails: 'Embedded content details…',
    removeVideo: 'Remove video',
    removeEmbed: 'Remove embedded content',
  }),
});
