import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { apiPageId, assertCoverage, groupApiPages } from './docs/api-group.mjs';
import { renderApiPage } from './docs/markdown.mjs';

const HEADER =
  '<!-- Do not edit this file. It is automatically generated by API Documenter. -->\n\n';
const crumbs = (...names) =>
  `[Home](./index.md) &gt; ${names.map((n) => `[${n}](./${n}.md)`).join(' &gt; ')}\n\n`;

const row = (link, desc = '') =>
  `<tr><td>\n\n${link}\n\n</td><td>\n\n${desc}\n\n</td></tr>\n`;
const table = (head, rows) =>
  `<table><thead><tr><th>\n\n${head}\n\n</th><th>\n\nDescription\n\n</th></tr></thead>\n<tbody>${rows.join('')}</tbody></table>\n\n`;

const FILES = {
  'rte-core-html.md':
    HEADER +
    crumbs('rte-core-html') +
    '## rte-core-html package\n\n## Functions\n\n' +
    table('Function', [
      row('[htmlToText(html)](./rte-core-html.htmltotext.md)', 'Converte.'),
      row('[ɵhelper()](./rte-core-html.ɵhelper.md)', 'Interno de verdade.'),
    ]) +
    '## Classes\n\n' +
    table('Class', [
      row('[Caixa](./rte-core-html.caixa.md)', 'Uma caixa.'),
      row('[Segredo](./rte-core-html.segredo.md)', 'Interna.'),
    ]),
  'rte-core-html.htmltotext.md':
    HEADER +
    crumbs('rte-core-html', 'rte-core-html.htmltotext') +
    '## htmlToText() function\n\nConverte HTML. Veja [Caixa](./rte-core-html.caixa.md) e [o tema](./rte-theme.md).\n\n**Signature:**\n\n```typescript\nexport declare function htmlToText(html: string): string;\n```\n\n## Parameters\n\n<table><thead><tr><th>\n\nParameter\n\n</th></tr></thead>\n<tbody><tr><td>\n\nhtml\n\n</td></tr>\n</tbody></table>\n',
  'rte-core-html.ɵhelper.md': HEADER + '## ɵhelper() function\n\nx\n',
  'rte-core-html.caixa.md':
    HEADER +
    crumbs('rte-core-html', 'rte-core-html.caixa') +
    '## Caixa class\n\nUma caixa.\n\n## Properties\n\n' +
    table('Property', [
      row('[ɵfac](./rte-core-html.caixa._fac.md)', ''),
      row('[largura](./rte-core-html.caixa.largura.md)', 'A largura.'),
    ]) +
    '## Methods\n\n' +
    table('Method', [row('[ɵmeth()](./rte-core-html.caixa._meth.md)', '')]),
  'rte-core-html.caixa._fac.md':
    HEADER + '## Caixa.ɵfac property\n\nstatic ɵfac\n',
  'rte-core-html.caixa._meth.md': HEADER + '## Caixa.ɵmeth() method\n\nx\n',
  'rte-core-html.caixa.largura.md':
    HEADER +
    crumbs('rte-core-html') +
    '## Caixa.largura property\n\nA largura em px.\n',
  'rte-core-html.segredo.md':
    HEADER + '## Segredo class\n\nNão publicar. @internal\n',
  'rte-theme.md':
    HEADER + crumbs('rte-theme') + '## rte-theme package\n\n## Functions\n\n',
};

const ENTRIES = [
  { synthetic: 'rte-core-html', specifier: '@comodeviaser/rte-core/html' },
  { synthetic: 'rte-theme', specifier: '@comodeviaser/rte-theme' },
];

function withDir(fn, files = FILES) {
  const dir = mkdtempSync(join(tmpdir(), 'docs-api-'));
  try {
    for (const [name, text] of Object.entries(files))
      writeFileSync(join(dir, name), text);
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test('api-group: uma página por entry com título = especificador', () => {
  withDir((markdownDir) => {
    const pages = groupApiPages({ markdownDir, entries: ENTRIES });
    assert.deepEqual(
      pages.map((p) => [p.id, p.title]),
      [
        ['api/core-html', '@comodeviaser/rte-core/html'],
        ['api/theme', '@comodeviaser/rte-theme'],
      ],
    );
    assert.equal(apiPageId('rte-angular-i18n'), 'api/angular-i18n');
  });
});

test('api-group: índice no topo, âncora por item e por membro, links reescritos', () => {
  withDir((markdownDir) => {
    const md = groupApiPages({ markdownDir, entries: ENTRIES })[0].markdown;
    assert.match(md, /^Especificador de importação: `@comodeviaser\/rte-core\/html`\./);
    assert.ok(
      md.indexOf('## Índice {#indice}') <
        md.indexOf('## htmlToText() function {#htmltotext}'),
    );
    assert.match(md, /## Caixa class \{#caixa\}/);
    assert.match(md, /### Caixa\.largura property \{#caixa\.largura\}/);
    // links `./x.y.md` -> `api/<entry>#<âncora>`; entry vizinho sem âncora; nenhum .md sobra
    assert.match(md, /\[htmlToText\(html\)\]\(api\/core-html#htmltotext\)/);
    assert.match(md, /\[o tema\]\(api\/theme\)/);
    assert.match(md, /\[Caixa\]\(api\/core-html#caixa\)/);
    assert.ok(!/\.md\)/.test(md.replace(/api\.md\)/, '')), 'sobrou link .md');
    assert.ok(
      !/\]\(\//.test(md.replace(/\]\(https:[^)]*\)/g, '')),
      'link iniciando por /',
    );
  });
});

test('api-group: membros ɵ* e itens @internal são omitidos (inclusive linhas e títulos órfãos)', () => {
  withDir((markdownDir) => {
    const md = groupApiPages({ markdownDir, entries: ENTRIES })[0].markdown;
    assert.ok(!md.includes('ɵ'), 'ɵ vazou');
    assert.ok(!/Segredo|@internal/.test(md), 'item interno vazou');
    // a seção "Methods" ficou sem membros públicos e some
    assert.ok(!/Methods/.test(md));
    assert.match(md, /### Properties \{#caixa-properties\}/);
  });
});

test('api-group: rodapé com o relatório congelado no GitHub', () => {
  withDir((markdownDir) => {
    const md = groupApiPages({ markdownDir, entries: ENTRIES })[0].markdown;
    assert.match(
      md,
      /\[rte-core-html\.api\.md\]\(https:\/\/github\.com\/[^)]*\/blob\/main\/packages\/core\/api\/rte-core-html\.api\.md\)\.$/,
    );
  });
});

test('api-group: a página passa pelo conversor e pela checagem X4', () => {
  withDir((markdownDir) => {
    const page = groupApiPages({ markdownDir, entries: ENTRIES })[0];
    const r = renderApiPage(page.markdown, { pageId: page.id });
    const html = r.segments[0].html;
    assert.match(html, /<h2 id="htmltotext">htmlToText\(\) function<\/h2>/);
    assert.match(html, /<h3 id="caixa\.largura">/);
    assert.match(html, /rel="noopener noreferrer"/);
    assert.deepEqual(
      r.headings.filter((h) => h.depth === 2).map((h) => h.id),
      ['indice', 'htmltotext', 'caixa'],
    );
  });
});

test('api-group: comentário JSDoc com HTML perigoso falha o build', () => {
  const files = {
    ...FILES,
    'rte-core-html.htmltotext.md':
      FILES['rte-core-html.htmltotext.md'] + '\n<script>alert(1)</script>\n',
  };
  withDir((markdownDir) => {
    const page = groupApiPages({ markdownDir, entries: ENTRIES })[0];
    assert.throws(
      () => renderApiPage(page.markdown, { pageId: page.id }),
      /api\/core-html: HTML não permitido[\s\S]*script/,
    );
  }, files);
});

test('api-group: entry sem arquivo do api-documenter falha', () => {
  const { 'rte-theme.md': _omit, ...rest } = FILES;
  void _omit;
  withDir((markdownDir) => {
    assert.throws(
      () => groupApiPages({ markdownDir, entries: ENTRIES }),
      /rte-theme.md/,
    );
  }, rest);
});

test('api-group: link para arquivo inexistente falha', () => {
  const files = {
    ...FILES,
    'rte-theme.md': FILES['rte-theme.md'] + '[x](./rte-theme.nada.md)\n',
  };
  withDir((markdownDir) => {
    assert.throws(
      () => groupApiPages({ markdownDir, entries: ENTRIES }),
      /sem arquivo\/entry correspondente/,
    );
  }, files);
});

test('assertCoverage: entry sem página e página sem entry falham', () => {
  const pages = [
    { specifier: '@comodeviaser/rte-core' },
    { specifier: '@comodeviaser/rte-extra' },
  ];
  assertCoverage(['@comodeviaser/rte-core'], [{ specifier: '@comodeviaser/rte-core' }]);
  assert.throws(
    () => assertCoverage(['@comodeviaser/rte-core', '@comodeviaser/rte-core/html'], [pages[0]]),
    /entry publicado "@comodeviaser\/rte-core\/html" sem página de API/,
  );
  assert.throws(
    () => assertCoverage(['@comodeviaser/rte-core'], pages),
    /página de API "@comodeviaser\/rte-extra" sem entry publicado/,
  );
  void mkdirSync;
});
